kubectl create ingress ingress-vh-routing --rule="/video=video-service:8080" --rule="/wear=apparels-service:8080"  --dry-run=client -o yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: ingress-vh-routing
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: video-service
            port:
              number: 8080
        path: /video
        pathType: Exact
      - backend:
          service:
            name: apparels-service
            port:
              number: 8080
        path: /wear
        pathType: Exact
status:
  loadBalancer: {}