apiVersion: v1
kind: Pod
metadata:
  namespace: dev2406
  labels:
    run: secret
  name: my-busybox
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: controlplane
  containers:
    - image: busybox
      name: secret
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
