apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dice
spec:
  schedule: '* * * * *'
  concurrencyPolicy: 'Forbid'
  jobTemplate:
    spec:
      backoffLimit: 25
      completions: 1
      activeDeadlineSeconds: 20
      template:
        spec:
          containers:
            - image: kodekloud/throw-dice
              name: throw-dice
          restartPolicy: Never
