apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-analytics
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/pv/data-analytics'



apiVersion: v1
kind: Pod
metadata:
  name: sega
spec:
  containers:
  - name: tails
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
  - name: sonic
    image: nginx
    env:
    - name: NGINX_PORT
      value: 8080

