apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: my-job
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: my-job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: busybox
              name: my-job
              resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
