apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30095
