apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  type: ClusterIP
  selector:
    app: metrics
    department: sales
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 8090
