apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      volumes:
        - name: drupal-storage
          persistentVolumeClaim:
            claimName: drupal-pvc
      containers:
        - name: drupal
          image: drupal:8.6
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/www/html/modules
              name: drupal-storage
              subPath: modules
            - mountPath: /var/www/html/profiles
              name: drupal-storage
              subPath: profiles
            - mountPath: /var/www/html/sites
              name: drupal-storage
              subPath: sites
            - mountPath: /var/www/html/themes
              name: drupal-storage
              subPath: themes
      initContainers:
        - name: init-sites-volume
          image: drupal:8.6
          command: ['/bin/bash', '-c']
          args:
            [
              'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R',
            ]
          volumeMounts:
            - mountPath: '/data'
              name: drupal-storage
