apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: jekyll
spec:
  ports:
    - name: jekyll
      port: 8080
      protocol: TCP
      targetPort: 4000
      nodePort: 30097
  selector:
    run: jekyll
  type: NodePort
