#
#
# PersistentVolume
#
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/opt/volume/nginx'
---
#
#
# PersistentVolumeClaim
#
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
---
#
#
# Pod
#
#
apiVersion: v1
kind: Pod
metadata:
  name: logger
spec:
  containers:
    - image: nginx:alpine
      name: nginx
      volumeMounts:
        - mountPath: /var/www/nginx
          name: logs
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: log-claim
