apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  type: NodePort
  selector:
    name: drupal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31200
