apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gop-fileserver
  name: gop-fileserver
spec:
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
  containers:
    - image: kodekloud/fileserver
      name: gop-fileserver
      resources: {}
      volumeMounts:
        - mountPath: /web
          name: data-store
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
